apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-volume
  labels:
    app: odoo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/jerome/Documents/postgresdata"