# helm install syslog-odoo -f values.yaml bitnami/odoo --version 23.0.0 -n syslog-odoo

odooEmail: "jerome@syslogsolution.com"

resources:
  requests:
    memory: 2Gi
    cpu: 2000m
  limits:
    memory: 4Gi
    cpu: 4000m

postgresql:
  enabled: true
  postgresqlUsername: odoo
  postgresqlDatabase: odoo
