# helm install syslog-odoo -f values.yaml bitnami/odoo --version 23.0.0 -n syslog-odoo
odooUsername: odoo
odooEmail: "jerome@syslogsolution.com"
adminPassword: "admin"
service:
  type: ClusterIP
  port: 8069
resources:
  requests:
    memory: 2Gi
    cpu: 1000m
persistentVolume:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
postgresql:
  enabled: true
  postgresqlPassword: "admin"
  persistence:
    enabled: true
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
livelinessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1