---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapps-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapps-operator
subjects:
- kind: ServiceAccount
  name: kubeapps-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
